name: Sound Synthesis From Scratch

collections:
  examples:
    output: true

category-list: [oscillator, interact, envelope, modulation, filter, synthesis, waveguide, diffeq]

baseurl: /synthfromscratch